import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/dashboardmain">Dashboardmain</Link>
        </li>
        <li>
          <Link to="/createbill">CreateBill</Link>
        </li>
        <li>
          <Link to="/viewbill">ViewBill</Link>
        </li>
        <li>
          <Link to="/viewbillone">ViewBillOne</Link>
        </li>
        <li>
          <Link to="/editbill">EditBill</Link>
        </li>
        <li>
          <Link to="/editalert">EditAlert</Link>
        </li>
        <li>
          <Link to="/addproducedproducts">AddProducedProducts</Link>
        </li>
        <li>
          <Link to="/addfarmproductsthree">AddFarmProductsThree</Link>
        </li>
        <li>
          <Link to="/editproduct">EditProduct</Link>
        </li>
        <li>
          <Link to="/editproductone">EditProductOne</Link>
        </li>
        <li>
          <Link to="/addfarmproductstwo">AddFarmProductsTwo</Link>
        </li>
        <li>
          <Link to="/addfarmproductsone">AddFarmProductsOne</Link>
        </li>
        <li>
          <Link to="/addfarmproducts">AddFarmProducts</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
